plugins{ 
    id 'java'
    id 'application'
}

repositories{
    mavenCentral()
}

dependencies{
    // only adding Junit for our TDD workflow
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.10.0'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.10.0'
}

application{
    mainClass = 'com.example.app.Main'
}

test{
    useJUnitPlatform()
}